all:
		gcc a2q1_a.c -o a2q1_a && ./a2q1_a
		gcc a2q1_b.c -o a2q1_b && ./a2q1_b
		gcc a2q2_a.c -o a2q2_a && ./a2q2_a
		gcc a2q2_b.c -o a2q2_b && ./a2q2_b
		gcc a2q2_c_stacks.c -o a2q2_c_stacks && ./a2q2_c_stacks
		gcc a2q2_c_queue.c -o a2q2_c_stacks.c && ./a2q2_c_queue
		gcc a2q3.c -o a2q3 && ./a2q3 
		gcc a2q5.c -o a2q5 && ./a2q5
		